/**
 * Mission Planning System Types
 *
 * Core entity types for the Mission Planning system that breaks down
 * large projects into phases and tasks, each executing through the
 * Dure agent pipeline (REFINE → BUILD → VERIFY → GATE).
 */

import type { MissionId, PhaseId, TaskId } from './branded.js';
import type { AgentModel } from './index.js';

// ============================================================================
// Granularity Type
// ============================================================================

/**
 * Execution granularity for missions
 * - 'task': Execute each task as a separate run
 * - 'phase': Execute each phase as a batch
 * - 'auto': Let the system decide based on complexity
 */
export type Granularity = 'task' | 'phase' | 'auto';

// ============================================================================
// Critique Types (Task 1.4)
// ============================================================================

/**
 * Severity level of a critique item
 */
export type CritiqueSeverity =
  | 'critical'    // Must be fixed before proceeding
  | 'major'       // Should be fixed
  | 'minor'       // Nice to fix
  | 'suggestion'; // Optional improvement

/**
 * Category of critique feedback
 */
export type CritiqueCategory =
  | 'missing_task'       // Task is missing from the plan
  | 'duplicate_task'     // Task appears to be duplicated
  | 'dependency_error'   // Dependency graph has issues
  | 'scope_issue'        // Task scope too large or too small
  | 'ordering_issue'     // Task order is suboptimal
  | 'unclear_spec'       // Task specification is unclear
  | 'missing_artifact'   // Expected artifact is not defined
  | 'security_concern'   // Potential security issue
  | 'other';

/**
 * Individual critique item
 */
export interface CritiqueItem {
  id: string;                         // critique-001, critique-002, ...
  severity: CritiqueSeverity;
  category: CritiqueCategory;
  target: {
    type: 'mission' | 'phase' | 'task';
    id?: string;                      // phase_id or task_id
  };
  title: string;                      // Brief summary
  description: string;                // Detailed explanation
  suggestion?: string;                // Suggested improvement
  resolved?: boolean;                 // Whether resolved in next iteration
}

/**
 * Complete critique from Critic agent
 * Reviews a plan draft and provides structured feedback
 */
export interface Critique {
  version: number;                    // Which iteration this critique is for
  created_at: string;

  // Overall verdict
  verdict: 'approved' | 'needs_revision' | 'needs_human';
  summary: string;                    // Overall summary

  // Individual feedback items
  items: CritiqueItem[];

  // Statistics
  stats: {
    critical: number;
    major: number;
    minor: number;
    suggestion: number;
  };

  // Rationale for verdict
  rationale: string;
}

/**
 * Critique auto-approve threshold
 * Plan is auto-approved if critique meets these criteria
 */
export const CRITIQUE_AUTO_APPROVE_THRESHOLD = {
  critical: 0,
  major: 0,
  minor: 3,
} as const;

// ============================================================================
// CarryForward Types (Task 1.4)
// ============================================================================

/**
 * CarryForward - context passed from one task to dependent tasks
 * Generated by Gatekeeper after a task completes successfully
 */
export interface CarryForward {
  task_id: TaskId;
  created_at: string;

  /**
   * Key decisions made in this task
   * @example ["JWT authentication selected", "Redis for session storage"]
   */
  key_decisions: string[];

  /**
   * Main artifacts created (files, directories)
   * @example ["src/auth/", "src/middleware/auth.ts"]
   */
  created_artifacts: string[];

  /**
   * API contracts defined (if any)
   * @example ["POST /auth/login", "GET /auth/refresh"]
   */
  api_contracts?: string[];

  /**
   * Data schemas defined (if any)
   * @example ["User { id, email, passwordHash }"]
   */
  data_schemas?: string[];

  /**
   * Warnings for future tasks
   * @example ["Rate limiting not implemented - needed in Phase 2"]
   */
  warnings: string[];

  /**
   * Suggestions for future tasks
   */
  suggestions?: string[];

  /**
   * Dependencies added to project
   * @example ["jsonwebtoken@9.0.0", "bcrypt@5.1.0"]
   */
  dependencies_added?: string[];

  /**
   * Configuration changes made
   */
  config_changes?: string[];
}

/**
 * PhaseContext - compressed context for the next phase
 * Generated by combining CarryForward from all tasks in a phase
 */
export interface PhaseContext {
  phase_id: PhaseId;
  phase_number: number;
  created_at: string;

  /**
   * Phase summary for LLM consumption
   */
  summary: string;

  /**
   * All key decisions from the phase
   */
  all_decisions: string[];

  /**
   * All artifacts created in the phase
   */
  all_artifacts: string[];

  /**
   * All API contracts from the phase
   */
  all_api_contracts: string[];

  /**
   * All warnings from the phase
   */
  all_warnings: string[];

  /**
   * Structured context for next phase
   * Used by Planner when generating next phase briefings
   */
  next_phase_context: string;
}

/**
 * Extended Gatekeeper verdict for Mission context
 * Includes carry_forward information
 */
export interface MissionGatekeeperVerdict {
  verdict: 'PASS' | 'FAIL' | 'NEEDS_HUMAN';
  reason: string;

  // Mission-specific: must generate carry_forward on PASS
  carry_forward?: CarryForward;

  // Standard gatekeeper fields
  suggestions?: string[];
  blocking_issues?: string[];
}

// ============================================================================
// Task Types
// ============================================================================

/**
 * Status of an individual task within a phase
 */
export type MissionTaskStatus =
  | 'pending'      // Waiting to be executed
  | 'blocked'      // Waiting for dependencies to complete
  | 'in_progress'  // Currently executing
  | 'passed'       // Successfully completed
  | 'failed'       // Execution failed
  | 'skipped'      // Intentionally skipped
  | 'needs_human'; // Requires human intervention

/**
 * Agent configuration override for a specific task
 * Allows per-task customization of agent behavior and models
 */
export interface AgentConfigOverride {
  model_selection?: {
    builder?: AgentModel;
    verifier?: AgentModel;
  };
  max_iterations?: number;
  timeout_ms?: number;
}

/**
 * Individual task within a phase
 * Each task runs through the full Dure pipeline (REFINE → BUILD → VERIFY → GATE)
 */
export interface MissionTask {
  task_id: TaskId;
  phase_id: PhaseId;
  title: string;                      // Brief descriptive title
  description: string;                // Detailed task description
  briefing_path: string;              // Path to briefing.md file

  // Agent configuration
  agent_config?: AgentConfigOverride; // Optional per-task agent settings

  // Dependencies
  depends_on: TaskId[];               // Tasks that must complete before this one

  // Execution state
  status: MissionTaskStatus;
  run_id?: string;                    // Associated Run ID once executed
  started_at?: string;                // ISO timestamp
  completed_at?: string;              // ISO timestamp
  error?: string;                     // Error message if failed

  // Results
  carry_forward?: CarryForward;       // Output from Gatekeeper to pass to dependent tasks
}

// ============================================================================
// Phase Types
// ============================================================================

/**
 * Status of a phase (collection of tasks)
 */
export type PhaseStatus =
  | 'pending'       // Not started yet
  | 'in_progress'   // At least one task is running
  | 'completed'     // All tasks completed successfully
  | 'failed'        // One or more tasks failed
  | 'needs_human';  // Human intervention required

/**
 * Summary generated when a phase completes
 * Provides context for the next phase
 */
export interface PhaseSummary {
  phase_id: PhaseId;
  completed_at: string;
  tasks_completed: number;
  tasks_failed: number;
  tasks_skipped: number;
  key_artifacts: string[];            // Important files created in this phase
  context_for_next: string;           // Compressed context for next phase
}

/**
 * MissionPhase - a logical grouping of related tasks
 * Tasks within a phase may have dependencies on each other
 * (Named MissionPhase to avoid conflict with execution Phase type)
 */
export interface MissionPhase {
  phase_id: PhaseId;
  mission_id: MissionId;
  number: number;                     // Phase number (1, 2, 3, ...)
  title: string;                      // Phase title
  description: string;                // Phase description

  tasks: MissionTask[];               // All tasks in this phase

  // State
  status: PhaseStatus;
  started_at?: string;
  completed_at?: string;

  // Summary generated when phase completes
  summary?: PhaseSummary;
}

// ============================================================================
// Mission Types
// ============================================================================

/**
 * Overall mission status
 */
export type MissionStatus =
  | 'planning'        // Planner/Critic agents are designing the mission
  | 'plan_review'     // Waiting for human approval of the plan
  | 'ready'           // Plan approved, ready to execute
  | 'in_progress'     // Executing tasks
  | 'completed'       // All phases and tasks completed
  | 'failed'          // Mission failed
  | 'cancelled';      // Mission cancelled by user

/**
 * Planning stage during mission initialization
 * Uses Planner and Critic agents to iterate on the plan
 */
export type PlanningStage =
  | 'planner_v1'      // First planning draft
  | 'critic_v1'       // First critique
  | 'planner_v2'      // Revised plan after first critique
  | 'critic_v2'       // Second critique
  | 'approved'        // Plan approved (by critic or human)
  | 'needs_human';    // Requires human review

/**
 * Draft plan created by Planner agent
 */
export interface PlanDraft {
  version: number;                    // Plan version (1 or 2)
  created_at: string;
  phases: Omit<MissionPhase, 'status' | 'started_at' | 'completed_at' | 'summary'>[];
}

/**
 * Statistics about mission progress
 */
export interface MissionStats {
  total_phases: number;
  total_tasks: number;
  completed_tasks: number;
  failed_tasks: number;
  current_phase?: number;             // Current phase number
}

/**
 * Mission - the top-level entity representing a multi-phase project
 *
 * Workflow:
 * 1. Planning: Planner/Critic iterate to create a multi-phase plan
 * 2. Review: Human reviews and approves the plan
 * 3. Execution: Tasks execute sequentially/in-parallel based on dependencies
 * 4. Completion: All tasks complete, mission summary generated
 */
export interface Mission {
  mission_id: MissionId;
  title: string;                      // Brief mission title
  description: string;                // Original mission description from user

  // Planning phase
  planning: {
    stage: PlanningStage;
    iterations: number;               // Number of Planner/Critic iterations (max 2)
    drafts: PlanDraft[];              // Plan versions
    critiques: Critique[];            // Critiques from Critic agent
  };

  // Execution structure
  phases: MissionPhase[];

  // Overall state
  status: MissionStatus;
  created_at: string;
  updated_at: string;
  completed_at?: string;

  // Statistics
  stats: MissionStats;
}

// ============================================================================
// Kanban Types (Phase 4)
// ============================================================================

/**
 * Kanban card representing a task on the board
 */
export interface KanbanCard {
  task_id: TaskId;
  phase_id: PhaseId;
  title: string;
  status: MissionTaskStatus;
  run_id?: string;
  error?: string;
  depends_on: TaskId[];
  blocked_by: TaskId[];              // Tasks that are actually blocking this one
}

/**
 * Kanban column representing a phase
 */
export interface KanbanColumn {
  phase_id: PhaseId;
  number: number;
  title: string;
  status: PhaseStatus;
  cards: KanbanCard[];
}

/**
 * Kanban board statistics
 */
export interface KanbanStats {
  total_tasks: number;
  pending: number;
  blocked: number;
  in_progress: number;
  passed: number;
  failed: number;
  needs_human: number;
}

/**
 * Active task information
 */
export interface KanbanActiveTask {
  task_id: TaskId;
  phase_id: PhaseId;
  run_id?: string;
  started_at: string;
}

/**
 * Complete Kanban board state
 */
export interface KanbanState {
  mission_id: MissionId;
  mission_title: string;
  planning_stage: PlanningStage;

  columns: KanbanColumn[];

  // Statistics
  stats: KanbanStats;

  // Currently executing task (if any)
  active_task?: KanbanActiveTask;

  // Last update timestamp
  updated_at: string;
}

/**
 * Kanban update event for real-time notifications
 */
export interface KanbanUpdate {
  type: 'task_status' | 'phase_status' | 'full_refresh';
  task_id?: TaskId;
  phase_id?: PhaseId;
  old_status?: string;
  new_status?: string;
  timestamp: string;
}
