#!/usr/bin/env python3
"""dure-index.py — regenerate .dure/roadmap/index.md from per-item files (I1.3.2).

The per-item files (roadmap/{milestones,epics,issues}/<id>.md) are the source of truth;
index.md is a GENERATED summary tree (never hand-edit). Deterministic: the same per-item
files produce a byte-identical index (idempotent), so it stays in sync and diffs cleanly.

Hierarchy order: a milestone's `epics:[]` order, then any epic whose `milestone:` points here;
an epic's `issues:[]` order, then any issue whose `epic:` points here. Items with no backing
file are NOT listed (use roadmap.md for the planning overview). Exit 0; 2 on error.
"""
import os
import re
import sys

try:
    import yaml
    HAVE_YAML = True
except Exception:  # noqa: BLE001
    HAVE_YAML = False

ROOT = os.environ.get("CLAUDE_PROJECT_DIR", os.getcwd())
RD = os.path.join(ROOT, ".dure", "roadmap")
STATUS_MARK = {"todo": "·", "doing": "◐", "done": "✓", "blocked": "✗"}
HEADER = ("<!-- GENERATED by dure-index.py — do not edit. "
          "Source of truth: roadmap/{milestones,epics,issues}/<id>.md -->")


def read_fm(path):
    txt = open(path, encoding="utf-8").read()
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", txt, re.S)
    if not m:
        return {}
    block = m.group(1)
    if HAVE_YAML:
        try:
            return yaml.safe_load(block) or {}
        except Exception:  # noqa: BLE001
            return {}
    data = {}
    for raw in block.splitlines():
        line = re.sub(r"\s+#.*$", "", raw)
        mm = re.match(r"^([\w.-]+):\s*(.*)$", line)
        if not mm:
            continue
        k, v = mm.group(1), mm.group(2).strip()
        if v.startswith("[") and v.endswith("]"):
            inner = v[1:-1].strip()
            data[k] = [x.strip() for x in inner.split(",") if x.strip()] if inner else []
        elif v.lower() in ("null", "~", ""):
            data[k] = None
        else:
            data[k] = v.strip('"').strip("'")
    return data


def load(kind):
    out = {}
    d = os.path.join(RD, kind)
    if os.path.isdir(d):
        for fn in sorted(os.listdir(d)):
            if fn.endswith(".md"):
                fm = read_fm(os.path.join(d, fn))
                if fm.get("id"):
                    out[fm["id"]] = fm
    return out


def fmt(item, indent):
    mark = STATUS_MARK.get(item.get("status"), "?")
    return f"{'  ' * indent}- {mark} **{item['id']}** {item.get('title', '')} · `{item.get('status', '')}`"


def main():
    milestones, epics, issues = load("milestones"), load("epics"), load("issues")
    lines = [HEADER, "", "# dure roadmap index (generated)", ""]
    used_e, used_i = set(), set()

    def emit_issue(iid, indent):
        if iid in issues and iid not in used_i:
            used_i.add(iid)
            lines.append(fmt(issues[iid], indent))

    def emit_epic(eid, indent):
        if eid in epics and eid not in used_e:
            used_e.add(eid)
            lines.append(fmt(epics[eid], indent))
            for iid in (epics[eid].get("issues") or []):
                emit_issue(iid, indent + 1)
            for iid in sorted(issues):
                if issues[iid].get("epic") == eid:
                    emit_issue(iid, indent + 1)

    for mid in sorted(milestones):
        lines.append(fmt(milestones[mid], 0))
        for eid in (milestones[mid].get("epics") or []):
            emit_epic(eid, 1)
        for eid in sorted(epics):
            if epics[eid].get("milestone") == mid:
                emit_epic(eid, 1)

    leftover_e = [e for e in sorted(epics) if e not in used_e]
    leftover_i = [i for i in sorted(issues) if i not in used_i]
    if leftover_e or leftover_i:
        lines += ["", "## Unlinked"]
        for eid in leftover_e:
            emit_epic(eid, 0)
        for iid in leftover_i:
            emit_issue(iid, 0)

    text = "\n".join(lines).rstrip() + "\n"
    try:
        os.makedirs(RD, exist_ok=True)
        open(os.path.join(RD, "index.md"), "w", encoding="utf-8").write(text)
    except OSError as e:
        print(f"dure-index: error: {e}", file=sys.stderr)
        sys.exit(2)
    print(f"dure-index: wrote roadmap/index.md "
          f"({len(milestones)} milestones, {len(epics)} epics, {len(issues)} issues)")


if __name__ == "__main__":
    main()
